# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0049_rackreservation_change_user'),
        ('ipam', '0020_ipaddress_add_role_carp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlangroup',
            options={'ordering': ['site', 'name', 'outervid'], 'verbose_name': 'VLAN group', 'verbose_name_plural': 'VLAN groups'},
        ),
        migrations.AddField(
            model_name='vlangroup',
            name='outervid',
            field=models.PositiveSmallIntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)], verbose_name='Outer ID'),
        ),
        migrations.AlterUniqueTogether(
            name='vlangroup',
            unique_together=set([('site', 'name'), ('site', 'slug'), ('site', 'outervid')]),
        ),
    ]
