# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0021_outer_vlan_id'),
        ('ipam', '0021_vrf_ordering'),
    ]

    operations = [
    ]
