# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0022_merge_20180226_0944'),
        ('ipam', '0022_merge_20180222_0733'),
        ('ipam', '0023_package_model'),
    ]

    operations = [
    ]
