# Generated by Django 2.0.9 on 2018-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0024_merge_20180307_1048'),
        ('ipam', '0023_change_logging'),
    ]

    operations = [
    ]
