# Generated by Django 2.2.1 on 2019-05-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0024_vrf_allow_null_rd'),
        ('ipam', '0025_merge_20181012_0920'),
    ]

    operations = [
    ]
