# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_package_model'),
        ('circuits', '0009_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package', to='tenancy.Package'),
        ),
        migrations.AlterField(
            model_name='circuittermination',
            name='term_side',
            field=models.CharField(choices=[('A', 'A'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, verbose_name='Termination'),
        ),
    ]
