# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0010_circuit_package'),
        ('circuits', '0010_circuit_status'),
    ]

    operations = [
    ]
