# Generated by Django 2.0.9 on 2018-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0011_merge_20180301_1214'),
        ('circuits', '0012_change_logging'),
    ]

    operations = [
    ]
