# Generated by Django 2.1.4 on 2019-01-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0014_optional_port_speed_circuit_terminations'),
        ('circuits', '0014_circuittermination_description'),
    ]

    operations = [
    ]
