# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_unicode_literals'),
        ('dcim', '0049_rackreservation_change_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='dhcp_enabled',
            field=models.BooleanField(default=False, verbose_name='DHCP enabled'),
        ),
        migrations.AddField(
            model_name='interface',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interface', to='tenancy.Tenant'),
        ),
    ]
