# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0055_virtualchassis_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[[100, 'Access'], [200, 'Tagged'], [400, 'Double Tagged'], [300, 'Tagged All']], null=True),
        ),
    ]
