# Generated by Django 2.0.9 on 2018-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0056_double_tagged_vlans'),
        ('dcim', '0063_device_local_context_data'),
    ]

    operations = [
    ]
