# Generated by Django 2.1.4 on 2019-01-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0065_latitude_decimal_fix'),
        ('dcim', '0068_rack_new_fields'),
    ]

    operations = [
    ]
