# Generated by Django 2.2.1 on 2019-05-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_deprecate_nullablecharfield'),
        ('dcim', '0069_merge_20190128_1143'),
    ]

    operations = [
    ]
