# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import extras.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0023_package_model'),
        ('tenancy', '0003_unicode_literals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('ipv4_enabled', models.BooleanField(default=True, help_text='Customers recieve an IPv4 address', verbose_name='IPv4 is enabled')),
                ('ipv6_enabled', models.BooleanField(default=True, help_text='Customers recieve an IPv6 address', verbose_name='IPv6 is enabled')),
                ('multicast_enabled', models.BooleanField(default=True, help_text='Customers can use multicast', verbose_name='Multicast is enabled')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(0, 'Static configuration'), (1, 'Dynamic configuration')], default=1, help_text='Static or dynamic configuration', verbose_name='Service type')),
                ('speed_upload', models.PositiveIntegerField(verbose_name='Upload speed rate (Kbps)')),
                ('speed_download', models.PositiveIntegerField(verbose_name='Download speed rate (Kbps)')),
                ('qos_profile', models.CharField(max_length=30)),
                ('tag_type', models.PositiveSmallIntegerField(choices=[(0, 'Untagged port'), (1, 'Single tagged port'), (2, 'Double tagged port')], default=2, help_text='Customers provide any VLAN tags', verbose_name='Tag type')),
                ('dhcp_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefixes', to='ipam.Prefix')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tenancy.TenantGroup')),
            ],
            options={
                'ordering': ['group', 'name'],
            },
            bases=(models.Model, extras.models.CustomFieldModel),
        ),
    ]
