# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_package_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='tenantgroup',
            options={'ordering': ['name'], 'verbose_name': 'Service Provider', 'verbose_name_plural': 'Service Providers'},
        ),
    ]
