# Generated by Django 2.0.9 on 2018-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_auto_20180308_1308'),
        ('tenancy', '0005_change_logging'),
    ]

    operations = [
    ]
