# Generated by Django 2.0.9 on 2018-10-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_merge_20181012_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tag_type',
        ),
        migrations.AlterField(
            model_name='package',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tenancy.TenantGroup'),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
