# Generated by Django 2.0.9 on 2018-10-17 08:08

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('tenancy', '0006_merge_20181012_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tag_type',
        ),
        migrations.AddField(
            model_name='package',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tenancy.TenantGroup'),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
