# Generated by Django 2.0.9 on 2018-11-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_package-update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='dhcp_pool',
        ),
        migrations.RemoveField(
            model_name='package',
            name='group',
        ),
        migrations.RemoveField(
            model_name='package',
            name='service_type',
        ),
    ]
